"""empty message

Revision ID: 460e62681126
Revises: 68e5b35fa055
Create Date: 2021-04-18 14:16:57.258085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460e62681126'
down_revision = '68e5b35fa055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guide', sa.Column('title', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guide', 'title')
    # ### end Alembic commands ###
